version: "3.7"

services:
  db-leader:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxca
      POSTGRES_DB: motion-db
    volumes:
      - ./leader-data:/var- master-data:/var/lib/postgresql/data
      - ./master/init:/docker-entrypoint-initdb.d/lib/postgresql/data
    ports: 5432:5432
    networks:
      - psql-net

  db-replica1:
    image: postgres:15
    container_name: db-replica1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxca
    depends_on:
      - db-leader
    volumes:
      - replica1-data:/var/lib/postgresql/data
      - ./replica/init:/docker-entrypoint-initdb.d
    entrypoint: ["bash", "-c", "/docker-entrypoint-initdb.d/replica-init.sh"]
    networks:
      - psql-net

  db-replica2:
    image: postgres:15
    container_name: db-replica2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db-leader
    volumes:
      - replica2-data:/var/lib/postgresql/data
      - ./replica/init:/docker-entrypoint-initdb.d
    entrypoint: ["bash", "-c", "/docker-entrypoint-initdb.d/replica-init.sh"]
    networks:
      - psql-net

  pgbouncer-write:
    image: edoburu/pgbouncer
    container_name: pgbouncer-write
    environment:
      DB_USER: postgres
      DB_PASSWORD: zxca
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer/write:/etc/pgbouncer
    depends_on:
      - db-leader
   networks:
      - psql-net

  pgbouncer-read:
    image: edoburu/pgbouncer
    container_name: pgbouncer-read
    environment:
      DB_USER: postgres
      DB_PASSWORD: zxca
    ports:
      - "6433:6432"
    volumes:
      - ./pgbouncer/read:/etc/pgbouncer
    depends_on:
      - db-replica1
      - db-replica2
    networks:
      - psql-net

volumes:
  master-data:
  replica1-data:
  replica2-data:

networks:
  psql-net:
    driver: bridge
