version: "3.8"

services:
  db-leader:
    image: postgres:15
    container_name: db-leader
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxca
      POSTGRES_DB: motion-db
    volumes:
      - leader-data:/var/lib/postgresql/data
      - ./leader:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - psql-net

  db-replica1:
    image: postgres:15
    container_name: db-replica1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxca
    volumes:
      - replica1-data:/var/lib/postgresql/data
      - ./replica/replica-entrypoint.sh:/docker-entrypoint-initdb.d/replica-entrypoint.sh
    depends_on:
      - db-leader
    networks:
      - psql-net

  db-replica2:
    image: postgres:15
    container_name: db-replica2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxca
    volumes:
      - replica2-data:/var/lib/postgresql/data
      - ./replica/replica-entrypoint.sh:/docker-entrypoint-initdb.d/replica-entrypoint.sh
    depends_on:
      - db-leader
    networks:
      - psql-net

  pgbouncer-write:
    image: edoburu/pgbouncer
    container_name: pgbouncer-write
    environment:
      DB_USER: postgres
      DB_PASSWORD: zxca
    volumes:
      - ./pgbouncer/write:/etc/pgbouncer
    ports:
      - "6432:6432"
    depends_on:
      - db-leader
    networks:
      - psql-net

  pgbouncer-read:
    image: edoburu/pgbouncer
    container_name: pgbouncer-read
    environment:
      DB_USER: postgres
      DB_PASSWORD: zxca
    volumes:
      - ./pgbouncer/read:/etc/pgbouncer
    ports:
      - "6433:6432"
    depends_on:
      - db-replica1
      - db-replica2
    networks:
      - psql-net

volumes:
  leader-data:
  replica1-data:
  replica2-data:

networks:
  psql-net:
    driver: bridge
